### ISSUE TITLE
New Species Images Displaying Incorrectly

### ISSUE THREAD

**Issue by MatteBailey** [huddlej/pnwmoths#246]
When clicking on the image of the live specimen of some species, the the image becomes mostly dark and shows only the label information.

**Comment by philipbjorge** [comment]
An additional issue is that the label information is not always located in the correct place.

**Comment by MatteBailey** [comment]
Images are displaying correctly after updating colorbox, but I believe labels are still out of place.

**Comment by philipbjorge** [comment]
Do you want to look into solving this one?
Basically, the solution will look something like this...
1. When colorbox is shown, you want to scroll to the top of the window. You also want to disable scrolling on the document (this will screw up the label positioning).

Disable scrolling means setting the following:

```
html, body { overflow: hidden }
```

You can do this in javascript.

So basically, you'll want to look into where I initialize colorbox and look at which callback function you need to implement.

---

The reason for doing it this way is because this was how I worked around the Zoomify plugin. If we force colorbox to behave the same way, then we don't have to modify the labels css.

**Comment by MatteBailey** [comment]
I changed the following two lines in fs_slideshow/script.js:

```
jQuery("#old-image-factsheet a").colorbox({
            onOpen:function(){ $("body").css('overflow', 'hidden');
            $(window).scrollTop(0); },
            onClosed:function(){ $("body").css('overflow', 'visible'); }
});
```

and

```
jQuery("#old-image-factsheet a").colorbox({
         onOpen:function(){ $("body").css('overflow', 'hidden');
         $(window).scrollTop(0); },
         onClosed:function(){ $("body").css('overflow', 'visible'); }
});
```

Everything seems to be working correctly now, assuming the label should be in the bottom-right of the screen.

I tried this javascript for disabling scrolling first:

```
document.body.style.overflow = "hidden";
```

But it wouldn't work. I'm still not too sure why.

**Comment by philipbjorge** [comment]
I'm not sure why `document.body.style.overflow = "hidden";` wouldn't work either. It worked when I executed it in the Chrome javascript console.

Either way, there's no problem with using jQuery for everything - It's better guaranteed to be completely cross browser compatible anyway.

---

There were a couple issues with your fix though.
1. Setting overflow: hidden effectively disables the scrollbar, so scrollTop does nothing. Reversing the order fixes it. First it brings you to the top of the page, then it prevents you from scrolling down.
2. This one is actually some trickery by colorbox - onOpen is called "when Colorbox is first opened, but after a few key variable assignments take place." These key variable assignments turned out to be important. Specifically they must've taken into account the position to show the image on the screen, because after scrollTop, the image wasn't positioned correctly.

So we need to call the scrollTop before colorbox even starts opening. To do this, I added a click handler before colorbox is initialized. This means that when the image is clicked on, my function followed by any other functions listening for clicks will get called.

```
         jQuery("#old-image-factsheet a").bind('click', function() {
                $(window).scrollTop(0);
                $("body").css('overflow', 'hidden');
         });
```

I kept your onClosed function!

Good work, they were tricky little bugs. I'll close this one as it's live on the server now.
