### ISSUE TITLE
Images don't load for species with hyphenated names

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#60]
For example:

Autographa v-alba
Xestia c-nigrum

**Comment by philipbjorge** [comment]
John
I noticed that this error only occurred on the PNWMoths server. I think this was an issue introduced by the script that converted the filesystem images into mysql records.

The problem is as follows:
Every image for Xestia c-nigrum is actually attributed to the species "Xestia c" (instead of "Xestia c-nigrum"). I'm going to run through and fix the affected images. I think this can be closed if we instruct people inputting the data to use the web interface?

**Comment by huddlej** [comment]
This data will likely always come primarily from the command line because it's easier to batch sync images. I have written a fix for this bug but haven't tested it yet.

**Comment by philipbjorge** [comment]
Tests were added in commit 6460e84125, so I'm marking this as closed.
