### ISSUE TITLE
Phenology should ignore incomplete date values

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#64]
The phenology script currently checks for records which are missing one or more of the three date values (day, month, and year), throws an alert to the user, and returns null.

This was based on the idea that there was something wrong with the data and an admin user should be alerted to fix it. However, from the phenology's perspective, these records should just be removed from the set of data to be plotted.

The relevant code starts in www/media/chart/script.js on line 170.

**Comment by philipbjorge** [comment]
Before I push to the fixes branch, I wanted to make sure I was understanding this correctly...

At the moment, every value in phenology_data[i][j] is initialized to 0. The only operation that is ever performed on phenology_data is "+= 1". So, phenology_data is guarenteed to be populated with integers.

When the data is flattened, no operations are performed on the values. So the flattened data is guarenteed to be populated with integers.

The relevant code on line 170 is looping through the flattened data and checking if any data points are NaNs. All the values in the flattened data are guarenteed to be 0 or some positive integer - so the entire block of code at 170 is dead. It's impossible to throw an alert. Debugging and messing around with values confirmed it.

Omitting data points is already being handled by sumDataByMonthAndSegment - it's ignoring data points with no month and/or day.

To conclude this long post, to fix this issue I'm proposing the following:
- Add a check in sumDataByMonthAndSegment to ignore data points with incomplete day/month/year   (Are you sure we want to exclude by year because we are currently only showing months?)
- Remove the block of code at 170 because we don't want alerts (and it doesn't do anything)

**Comment by huddlej** [comment]
Agreed. I know I've had that block of code throw an alert before, but that was when we used CouchDB and data might have been loaded differently.

I like your plan and agree that we shouldn't omit data points with missing years. We only need to check for month and day which already happens in sumDataByMonthAndSegment.

**Comment by philipbjorge** [comment]
Sounds good - I issued a pull request.
I'm a bit new to git, will merging my request also get rid of the fixes branch?
If so, what branching strategy would you recommend? Or would you just say make more fixes before issuing a pull request?

**Comment by huddlej** [comment]
I think what you did was perfect. Branching is safer because it helps us undo or refer to changes in the present and future. Pull requests let me know when you're ready for something to be reviewed.

And it looks like github's [auto merge does a --no-ff merge](https://github.com/blog/843-the-merge-button) and then removes the branch, so we never lose the history of the branch entirely.
